# Dockerfile.worker
FROM python:3.11-slim

RUN apt-get update && apt-get install -y git cloc && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["celery", "-A", "app.celery_config", "worker", "--loglevel=info", "-P", "gevent"]